let zeroBtn = document.getElementById('zeroBtn')
let oneBtn = document.getElementById('oneBtn')
let twoBtn = document.getElementById('twoBtn')
let threeBtn = document.getElementById('threeBtn')
let fourBtn = document.getElementById('fourBtn')
let fiveBtn = document.getElementById('fiveBtn')
let sixBtn = document.getElementById('sixBtn')
let sevenBtn = document.getElementById('sevenBtn')
let eightBtn = document.getElementById('eightBtn')
let nineBtn = document.getElementById('nineBtn')

let pointBtn = document.getElementById('pointBtn')

let calculatorScreen = document.getElementById('calculatorScreen')

let clearBtn = document.getElementById('clearBtn')
let sumBtn = document.getElementById('sumBtn')
let subtractionBtn = document.getElementById('subtractionBtn')
let divisionBtn = document.getElementById('divisionBtn')
let multiplicationBtn = document.getElementById('multiplicationBtn')
let equalBtn = document.getElementById('equalBtn')

zeroBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 0})
oneBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 1})
twoBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 2})
threeBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 3})
fourBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 4})
fiveBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 5})
sixBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 6})
sevenBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 7})
eightBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 8})
nineBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + 9})
pointBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + '.'})

clearBtn.addEventListener('click', () => {calculatorScreen.innerText = ''}) 
sumBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + '+'})
subtractionBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + '-'})
divisionBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + '/'})
multiplicationBtn.addEventListener('click', () => {calculatorScreen.innerText = calculatorScreen.innerText + '*'})

equalBtn.addEventListener('click', () => {calculatorScreen.innerText = Number(eval(calculatorScreen.innerText).toFixed(2))})
